name: dedisalam
services:
  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    restart: always
    ports:
      - "80:80"
      - "9000:9000"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      MYSQL_PASSWORD: 4r!M4n3hKuN40n
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_HOST: mysql.dedisalam
      REDIS_HOST: redis.dedisalam
      NEXTCLOUD_TRUSTED_DOMAINS: clouds.dedisalam.my.id
    networks:
      - cloudflare
      - dedisalam

volumes:
  nextcloud_data:
    name: nextcloud_data

networks:
  cloudflare:
    name: cloudflare
  dedisalam:
    name: dedisalam